import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';
import typography from '@tailwindcss/typography';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './vendor/laravel/jetstream/**/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './resources/js/**/*.vue',
    ],

    theme: {
        extend: {
            fontFamily: {
                sans: ['Figtree', ...defaultTheme.fontFamily.sans],
                heading: ['Figtree', ...defaultTheme.fontFamily.sans],
            },

            colors: {
                air: {
                    bg: '#f7fbff',
                    card: '#ffffff',
                    primary: '#102033',
                    secondary: '#5d6b7e',
                    success: '#22c55e',
                    error: '#ef4444',
                    border: '#d7e4ef',
                    borderHover: '#38bdf8',
                    muted: '#eaf4fb',
                    buttonPrimary: '#0ea5e9',
                    inputBg: '#ffffff',
                    table: '#f1f7fb',
                    buttonTextPrimary: '#ffffff',
                    buttonTextSecondary: '#123047',
                    buttonPrimaryHover: '#0284c7',
                    buttonTextPrimaryHover: '#ffffff',
                    buttonTextSecondaryHover: '#0ea5e9',
                    progress: '#0ea5e9',
                },

                dark: {
                    bg: '#0c1016',
                    card: '#121821',
                    primary: '#f4f7fb',
                    secondary: '#aab6c5',
                    success: '#34d399',
                    error: '#fb7185',
                    border: '#263241',
                    borderHover: '#60a5fa',
                    muted: '#1d2633',
                    buttonPrimary: '#f4f7fb',
                    inputBg: '#0f1520',
                    table: '#151b23',
                    buttonTextPrimary: '#0c1016',
                    buttonTextSecondary: '#f4f7fb',
                    buttonPrimaryHover: '#c7d2fe',
                    buttonTextPrimaryHover: '#101624',
                    buttonTextSecondaryHover: '#c7d2fe',
                    progress: '#60a5fa',
                },

                womanly: {
                    bg: '#fff7fb',
                    card: '#ffffff',
                    primary: '#43223b',
                    secondary: '#8a5b7d',
                    success: '#16a34a',
                    error: '#e11d48',
                    border: '#f1cfe0',
                    borderHover: '#db2777',
                    muted: '#fde8f2',
                    buttonPrimary: '#be185d',
                    inputBg: '#fffafd',
                    table: '#fff0f7',
                    buttonTextPrimary: '#ffffff',
                    buttonTextSecondary: '#5c294f',
                    buttonPrimaryHover: '#9d174d',
                    buttonTextPrimaryHover: '#ffffff',
                    buttonTextSecondaryHover: '#be185d',
                    progress: '#db2777',
                },

                bg: 'var(--bg)',
                card: 'var(--card)',
                primary: 'var(--primary)',
                secondary: 'var(--secondary)',
                success: 'var(--success)',
                error: 'var(--error)',
                border: 'var(--border)',
                borderHover: 'var(--borderHover)',
                muted: 'var(--muted)',
                buttonPrimary: 'var(--buttonPrimary)',
                inputBg: 'var(--inputBg)',
                table: 'var(--table)',
                buttonTextPrimary: 'var(--buttonTextPrimary)',
                buttonTextSecondary: 'var(--buttonTextSecondary)',
                buttonPrimaryHover: 'var(--buttonPrimaryHover)',
                buttonTextPrimaryHover: 'var(--buttonTextPrimaryHover)',
                buttonTextSecondaryHover: 'var(--buttonTextSecondaryHover)',
                progress: 'var(--progress)',
                'air-blue': 'var(--accent)',
                'air-green': 'var(--accent-2)',
                'air-orange': 'var(--accent-3)',
                'air-dark': 'var(--surface-strong)',
            },

            fontWeight: {
                600: '600',
                700: '700',
                800: '800',
                900: '900',
            },
        },
    },

    plugins: [forms, typography],
};
