import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';
import typography from '@tailwindcss/typography';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './vendor/laravel/jetstream/**/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './resources/js/**/*.vue',
    ],

    theme: {
        extend: {
            fontFamily: {
                sans: ['Figtree', ...defaultTheme.fontFamily.sans],
                heading: ['Figtree', ...defaultTheme.fontFamily.sans],
            },

            colors: {
                air: {
                    bg: '#f7fbff',
                    card: '#ffffff',
                    primary: '#102033',
                    secondary: '#5d6b7e',
                    success: '#22c55e',
                    error: '#ef4444',
                    border: '#d7e4ef',
                    borderHover: '#38bdf8',
                    muted: '#eaf4fb',
                    buttonPrimary: '#0ea5e9',
                    inputBg: '#ffffff',
                    table: '#f1f7fb',
                    buttonTextPrimary: '#ffffff',
                    buttonTextSecondary: '#123047',
                    buttonPrimaryHover: '#0284c7',
                    buttonTextPrimaryHover: '#ffffff',
                    buttonTextSecondaryHover: '#0ea5e9',
                    progress: '#0ea5e9',
                },

                dark: {
                    bg: '#0c1016',
                    card: '#121821',
                    primary: '#f4f7fb',
                    secondary: '#aab6c5',
                    success: '#34d399',
                    error: '#fb7185',
                    border: '#263241',
                    borderHover: '#60a5fa',
                    muted: '#1d2633',
                    buttonPrimary: '#f4f7fb',
                    inputBg: '#0f1520',
                    table: '#151b23',
                    buttonTextPrimary: '#0c1016',
                    buttonTextSecondary: '#f4f7fb',
                    buttonPrimaryHover: '#c7d2fe',
                    buttonTextPrimaryHover: '#101624',
                    buttonTextSecondaryHover: '#c7d2fe',
                    progress: '#60a5fa',
                },

                womanly: {
                    bg: '#fff7fb',
                    card: '#ffffff',
                    primary: '#43223b',
                    secondary: '#8a5b7d',
                    success: '#16a34a',
                    error: '#e11d48',
                    border: '#f1cfe0',
                    borderHover: '#db2777',
                    muted: '#fde8f2',
                    buttonPrimary: '#be185d',
                    inputBg: '#fffafd',
                    table: '#fff0f7',
                    buttonTextPrimary: '#ffffff',
                    buttonTextSecondary: '#5c294f',
                    buttonPrimaryHover: '#9d174d',
                    buttonTextPrimaryHover: '#ffffff',
                    buttonTextSecondaryHover: '#be185d',
                    progress: '#db2777',
                },

                champion: {
                    bg: '#fffaf0',
                    card: '#ffffff',
                    primary: '#2f2412',
                    secondary: '#7a5a22',
                    success: '#16a34a',
                    error: '#dc2626',
                    border: '#f2d89b',
                    borderHover: '#d97706',
                    muted: '#fff1c2',
                    buttonPrimary: '#b45309',
                    inputBg: '#fffdf7',
                    table: '#fff6d8',
                    buttonTextPrimary: '#ffffff',
                    buttonTextSecondary: '#4a3412',
                    buttonPrimaryHover: '#92400e',
                    buttonTextPrimaryHover: '#ffffff',
                    buttonTextSecondaryHover: '#b45309',
                    progress: '#d97706',
                },

                sprint: {
                    bg: '#f5fff9',
                    card: '#ffffff',
                    primary: '#0b2f24',
                    secondary: '#437063',
                    success: '#059669',
                    error: '#e11d48',
                    border: '#bfe8d8',
                    borderHover: '#10b981',
                    muted: '#dcfce7',
                    buttonPrimary: '#059669',
                    inputBg: '#fbfffd',
                    table: '#ecfdf5',
                    buttonTextPrimary: '#ffffff',
                    buttonTextSecondary: '#0f3f31',
                    buttonPrimaryHover: '#047857',
                    buttonTextPrimaryHover: '#ffffff',
                    buttonTextSecondaryHover: '#059669',
                    progress: '#10b981',
                },

                arena: {
                    bg: '#f8fafc',
                    card: '#ffffff',
                    primary: '#1e293b',
                    secondary: '#64748b',
                    success: '#16a34a',
                    error: '#dc2626',
                    border: '#cbd5e1',
                    borderHover: '#475569',
                    muted: '#e2e8f0',
                    buttonPrimary: '#334155',
                    inputBg: '#ffffff',
                    table: '#f1f5f9',
                    buttonTextPrimary: '#ffffff',
                    buttonTextSecondary: '#334155',
                    buttonPrimaryHover: '#1e293b',
                    buttonTextPrimaryHover: '#ffffff',
                    buttonTextSecondaryHover: '#1e293b',
                    progress: '#64748b',
                },

                pulse: {
                    bg: '#fff7ed',
                    card: '#ffffff',
                    primary: '#3b1d0f',
                    secondary: '#8a4b2a',
                    success: '#16a34a',
                    error: '#dc2626',
                    border: '#fed7aa',
                    borderHover: '#f97316',
                    muted: '#ffedd5',
                    buttonPrimary: '#ea580c',
                    inputBg: '#fffaf5',
                    table: '#fff3e0',
                    buttonTextPrimary: '#ffffff',
                    buttonTextSecondary: '#5f2f17',
                    buttonPrimaryHover: '#c2410c',
                    buttonTextPrimaryHover: '#ffffff',
                    buttonTextSecondaryHover: '#ea580c',
                    progress: '#f97316',
                },

                trail: {
                    bg: '#f6f8f2',
                    card: '#ffffff',
                    primary: '#24301b',
                    secondary: '#657252',
                    success: '#15803d',
                    error: '#dc2626',
                    border: '#d6dfc6',
                    borderHover: '#65a30d',
                    muted: '#edf5df',
                    buttonPrimary: '#4d7c0f',
                    inputBg: '#fbfdf7',
                    table: '#eef6e2',
                    buttonTextPrimary: '#ffffff',
                    buttonTextSecondary: '#31411f',
                    buttonPrimaryHover: '#3f6212',
                    buttonTextPrimaryHover: '#ffffff',
                    buttonTextSecondaryHover: '#4d7c0f',
                    progress: '#65a30d',
                },

                bg: 'var(--bg)',
                card: 'var(--card)',
                primary: 'var(--primary)',
                secondary: 'var(--secondary)',
                success: 'var(--success)',
                error: 'var(--error)',
                border: 'var(--border)',
                borderHover: 'var(--borderHover)',
                muted: 'var(--muted)',
                buttonPrimary: 'var(--buttonPrimary)',
                inputBg: 'var(--inputBg)',
                table: 'var(--table)',
                buttonTextPrimary: 'var(--buttonTextPrimary)',
                buttonTextSecondary: 'var(--buttonTextSecondary)',
                buttonPrimaryHover: 'var(--buttonPrimaryHover)',
                buttonTextPrimaryHover: 'var(--buttonTextPrimaryHover)',
                buttonTextSecondaryHover: 'var(--buttonTextSecondaryHover)',
                progress: 'var(--progress)',
                'air-blue': 'var(--accent)',
                'air-green': 'var(--accent-2)',
                'air-orange': 'var(--accent-3)',
                'air-dark': 'var(--surface-strong)',
            },

            fontWeight: {
                600: '600',
                700: '700',
                800: '800',
                900: '900',
            },
        },
    },

    plugins: [forms, typography],
};
