<?php

return [
    'sport_types' => [
        ['key' => 'running', 'label' => 'Laufen', 'label_key' => 'sport_map.sport_types.running', 'icon' => 'las la-running'],
        ['key' => 'trail_running', 'label' => 'Trailrunning', 'label_key' => 'sport_map.sport_types.trail_running', 'icon' => 'las la-mountain'],
        ['key' => 'cycling', 'label' => 'Radfahren', 'label_key' => 'sport_map.sport_types.cycling', 'icon' => 'las la-biking'],
        ['key' => 'mountainbike', 'label' => 'Mountainbike', 'label_key' => 'sport_map.sport_types.mountainbike', 'icon' => 'las la-biking'],
        ['key' => 'walking', 'label' => 'Gehen', 'label_key' => 'sport_map.sport_types.walking', 'icon' => 'las la-walking'],
        ['key' => 'wandern', 'label' => 'Wandern', 'label_key' => 'sport_map.sport_types.wandern', 'icon' => 'las la-hiking'],
        ['key' => 'football', 'label' => 'Fußball', 'label_key' => 'sport_map.sport_types.football', 'icon' => 'las la-futbol'],
        ['key' => 'skateboard', 'label' => 'Skateboard', 'label_key' => 'sport_map.sport_types.skateboard', 'icon' => 'las la-skating'],
        ['key' => 'fitness', 'label' => 'Outdoor-Fitness', 'label_key' => 'sport_map.sport_types.fitness', 'icon' => 'las la-dumbbell'],
        ['key' => 'other', 'label' => 'Andere Sportart', 'label_key' => 'sport_map.sport_types.other', 'icon' => 'las la-map-marker-alt'],
    ],

    'place_types' => [
        ['key' => 'football_pitch', 'label' => 'Fußballplatz', 'label_key' => 'sport_map.place_types.football_pitch', 'icon' => 'las la-futbol'],
        ['key' => 'running_track', 'label' => 'Laufbahn', 'label_key' => 'sport_map.place_types.running_track', 'icon' => 'las la-running'],
        ['key' => 'skatepark', 'label' => 'Skatepark', 'label_key' => 'sport_map.place_types.skatepark', 'icon' => 'las la-skating'],
        ['key' => 'basketball_court', 'label' => 'Basketballplatz', 'label_key' => 'sport_map.place_types.basketball_court', 'icon' => 'las la-basketball-ball'],
        ['key' => 'tennis_court', 'label' => 'Tennisplatz', 'label_key' => 'sport_map.place_types.tennis_court', 'icon' => 'las la-table-tennis'],
        ['key' => 'calisthenics_park', 'label' => 'Calisthenics-Park', 'label_key' => 'sport_map.place_types.calisthenics_park', 'icon' => 'las la-dumbbell'],
        ['key' => 'swimming_pool', 'label' => 'Schwimmbad', 'label_key' => 'sport_map.place_types.swimming_pool', 'icon' => 'las la-swimmer'],
        ['key' => 'climbing_spot', 'label' => 'Kletterspot', 'label_key' => 'sport_map.place_types.climbing_spot', 'icon' => 'las la-mountain'],
        ['key' => 'trailhead', 'label' => 'Trail-/Routenstart', 'label_key' => 'sport_map.place_types.trailhead', 'icon' => 'las la-route'],
        ['key' => 'sports_hall', 'label' => 'Sporthalle', 'label_key' => 'sport_map.place_types.sports_hall', 'icon' => 'las la-warehouse'],
        ['key' => 'other', 'label' => 'Anderer Sportplatz', 'label_key' => 'sport_map.place_types.other', 'icon' => 'las la-map-pin'],
    ],

    'map' => [
        'provider' => env('SPORT_MAP_TILE_PROVIDER', 'osm_public'),
        'tile_url' => env('SPORT_MAP_TILE_URL', 'https://tile.openstreetmap.org/{z}/{x}/{y}.png'),
        'attribution' => env('SPORT_MAP_ATTRIBUTION', '(c) OpenStreetMap contributors'),
        'satellite_tile_url' => env('SPORT_MAP_SATELLITE_TILE_URL', 'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}'),
        'satellite_attribution' => env('SPORT_MAP_SATELLITE_ATTRIBUTION', '(c) Esri, Maxar, Earthstar Geographics, and the GIS User Community'),
    ],

    'routing' => [
        'provider' => env('SPORT_MAP_ROUTING_PROVIDER', 'osrm'),
        'route_generator_provider' => env('SPORT_MAP_ROUTE_GENERATOR_PROVIDER', 'osrm'),
        'osrm_base_url' => env('SPORT_MAP_OSRM_BASE_URL', 'https://router.project-osrm.org'),
        'mapbox_base_url' => env('SPORT_MAP_MAPBOX_BASE_URL', 'https://api.mapbox.com'),
        'mapbox_access_token' => env('MAPBOX_ACCESS_TOKEN'),
        'timeout_seconds' => (int) env('SPORT_MAP_ROUTING_TIMEOUT', 4),
        'profiles' => [
            'running' => 'foot',
            'trail_running' => 'foot',
            'walking' => 'foot',
            'wandern' => 'foot',
            'cycling' => 'bike',
            'mountainbike' => 'bike',
            'skateboard' => 'foot',
            'fitness' => 'foot',
            'football' => 'foot',
            'other' => 'foot',
        ],
        'mapbox_profiles' => [
            'running' => 'walking',
            'trail_running' => 'walking',
            'walking' => 'walking',
            'wandern' => 'walking',
            'cycling' => 'cycling',
            'mountainbike' => 'cycling',
            'skateboard' => 'walking',
            'fitness' => 'walking',
            'football' => 'walking',
            'other' => 'walking',
        ],
    ],
];
