const sepaFeeRechargeLabels = <String, Map<String, String>>{
  'de': {
    'title': 'Gebühren weiterbelasten',
    'help':
        'Ein Vorschlag erzeugt erst nach der Freigabe durch eine andere berechtigte Person eine gesonderte Rechnung.',
    'current': 'Aktuelle Gebühr',
    'recipient': 'Empfänger',
    'basis': 'Prüfgrundlage',
    'reason': 'Begründung',
    'due': 'Fälligkeit',
    'amount': 'Vorgeschlagener Betrag in EUR',
    'account': 'Buchhaltungskonto',
    'proposal': 'Vorschlag erstellen',
    'approve': 'Weiterbelastung freigeben',
    'cancel': 'Vorschlag zurücknehmen',
    'requestVoid': 'Storno beantragen',
    'approveVoid': 'Storno freigeben',
    'withdrawVoid': 'Stornoantrag zurücknehmen',
    'basisConfirm':
        'Ich habe Grundlage, Empfänger, Betrag und Fälligkeit geprüft.',
    'confirm': 'Ich bestätige diese Aktion und die angezeigten Angaben.',
    'retry': 'Dieselbe Anfrage erneut senden',
    'reload': 'Aktuellen Stand laden',
    'uncertain':
        'Der Ausgang ist unklar. Eine Wiederholung sendet exakt dieselben Daten; es gibt keinen automatischen erneuten Versuch.',
    'review':
        'Erneute Prüfung erforderlich: Die zugrunde liegende Gebühr wurde geändert.',
    'empty': 'Noch keine Vorschläge.',
    'invoice': 'Gesonderte Rechnung',
    'voidRequest': 'Stornoantrag',
    'status_draft': 'Entwurf',
    'status_cancelled': 'Zurückgenommen',
    'status_approved': 'Freigegeben',
    'status_voided': 'Storniert',
    'status_credited': 'Gutgeschrieben',
    'void_pending': 'Ausstehend',
    'void_applied': 'Storno ausgeführt',
    'void_withdrawn': 'Zurückgenommen',
    'invoice_open': 'Offen',
    'invoice_overdue': 'Überfällig',
    'invoice_paid': 'Bezahlt',
    'invoice_cancelled': 'Storniert',
    'requestCredit': 'Gutschrift beantragen',
    'approveCredit': 'Gutschrift freigeben',
    'withdrawCredit': 'Gutschriftantrag zurücknehmen',
    'creditRequest': 'Gutschriftantrag',
    'creditNote': 'Gutschriftnummer',
    'creditDocument': 'Gutschrift als PDF öffnen',
    'documentError': 'Die Gutschrift konnte nicht geöffnet werden.',
    'refundDue': 'Offener Erstattungsbetrag',
    'refundEvidence': 'Erstattungsnachweis',
    'refund': 'Erstattung dokumentieren',
    'refundHelp':
        'Erst nach der tatsächlichen Auszahlung dokumentieren. Diese Aktion führt keine Überweisung aus.',
    'refundDate': 'Buchungsdatum der Erstattung',
    'refundReference': 'Bankreferenz der Erstattung',
    'financeEntry': 'Vorhandene Ausgabe-ID (optional)',
    'financeEntryHelp':
        'Leer lassen, um eine neue Bankausgabe anzulegen, oder die ID einer exakt passenden Ausgabe eintragen.',
    'credit_pending': 'Prüfung ausstehend',
    'credit_issued': 'Gutschrift erstellt – Erstattung offen',
    'credit_completed': 'Abgeschlossen – keine Erstattung nötig',
    'credit_refunded': 'Erstattung dokumentiert',
    'credit_withdrawn': 'Zurückgenommen',
    'error':
        'Die Aktion konnte nicht abgeschlossen werden. Bitte Angaben und aktuellen Stand prüfen.',
  },
  'en': {
    'title': 'Recharge fees',
    'help':
        'A proposal creates a separate invoice only after approval by another authorized person.',
    'current': 'Current fee',
    'recipient': 'Recipient',
    'basis': 'Review basis',
    'reason': 'Reason',
    'due': 'Due date',
    'amount': 'Proposed amount in EUR',
    'account': 'Accounting account',
    'proposal': 'Create proposal',
    'approve': 'Approve recharge',
    'cancel': 'Withdraw proposal',
    'requestVoid': 'Request void',
    'approveVoid': 'Approve void',
    'withdrawVoid': 'Withdraw void request',
    'basisConfirm': 'I reviewed the basis, recipient, amount and due date.',
    'confirm': 'I confirm this action and the displayed details.',
    'retry': 'Send the same request again',
    'reload': 'Load current state',
    'uncertain':
        'The outcome is uncertain. A retry sends exactly the same data; there is no automatic retry.',
    'review': 'Review required: the underlying fee changed.',
    'empty': 'No proposals yet.',
    'invoice': 'Separate invoice',
    'voidRequest': 'Void request',
    'status_draft': 'Draft',
    'status_cancelled': 'Withdrawn',
    'status_approved': 'Approved',
    'status_voided': 'Voided',
    'status_credited': 'Credited',
    'void_pending': 'Pending',
    'void_applied': 'Void completed',
    'void_withdrawn': 'Withdrawn',
    'invoice_open': 'Open',
    'invoice_overdue': 'Overdue',
    'invoice_paid': 'Paid',
    'invoice_cancelled': 'Cancelled',
    'requestCredit': 'Request credit note',
    'approveCredit': 'Approve credit note',
    'withdrawCredit': 'Withdraw credit request',
    'creditRequest': 'Credit request',
    'creditNote': 'Credit note number',
    'creditDocument': 'Open credit note PDF',
    'documentError': 'The credit note could not be opened.',
    'refundDue': 'Refund due',
    'refundEvidence': 'Refund evidence',
    'refund': 'Record refund',
    'refundHelp':
        'Record only after the actual payout. This action does not transfer money.',
    'refundDate': 'Refund booking date',
    'refundReference': 'Refund bank reference',
    'financeEntry': 'Existing expense ID (optional)',
    'financeEntryHelp':
        'Leave blank to create a bank expense, or enter the ID of an exact matching expense.',
    'credit_pending': 'Review pending',
    'credit_issued': 'Credit issued – refund pending',
    'credit_completed': 'Completed – no refund required',
    'credit_refunded': 'Refund recorded',
    'credit_withdrawn': 'Withdrawn',
    'error':
        'The action could not be completed. Check the details and current state.',
  },
  'fr': {
    'title': 'Refacturer les frais',
    'help':
        'Une proposition crée une facture distincte seulement après approbation par une autre personne autorisée.',
    'current': 'Frais actuels',
    'recipient': 'Destinataire',
    'basis': 'Fondement à vérifier',
    'reason': 'Motif',
    'due': 'Échéance',
    'amount': 'Montant proposé en EUR',
    'account': 'Compte comptable',
    'proposal': 'Créer une proposition',
    'approve': 'Approuver la refacturation',
    'cancel': 'Retirer la proposition',
    'requestVoid': 'Demander l’annulation',
    'approveVoid': 'Approuver l’annulation',
    'withdrawVoid': 'Retirer la demande',
    'basisConfirm':
        'J’ai vérifié le fondement, le destinataire, le montant et l’échéance.',
    'confirm': 'Je confirme cette action et les données affichées.',
    'retry': 'Renvoyer la même demande',
    'reload': 'Charger l’état actuel',
    'uncertain':
        'Le résultat est incertain. Un nouvel essai envoie exactement les mêmes données, sans essai automatique.',
    'review': 'Nouvelle vérification requise : les frais ont changé.',
    'empty': 'Aucune proposition.',
    'invoice': 'Facture distincte',
    'voidRequest': 'Demande d’annulation',
    'status_draft': 'Brouillon',
    'status_cancelled': 'Retirée',
    'status_approved': 'Approuvée',
    'status_voided': 'Annulée',
    'status_credited': 'Créditée',
    'void_pending': 'En attente',
    'void_applied': 'Annulation effectuée',
    'void_withdrawn': 'Retirée',
    'invoice_open': 'Ouverte',
    'invoice_overdue': 'En retard',
    'invoice_paid': 'Payée',
    'invoice_cancelled': 'Annulée',
    'requestCredit': 'Demander un avoir',
    'approveCredit': 'Approuver l’avoir',
    'withdrawCredit': 'Retirer la demande d’avoir',
    'creditRequest': 'Demande d’avoir',
    'creditNote': 'Numéro de l’avoir',
    'creditDocument': 'Ouvrir l’avoir en PDF',
    'documentError': 'Impossible d’ouvrir l’avoir.',
    'refundDue': 'Remboursement dû',
    'refundEvidence': 'Preuve du remboursement',
    'refund': 'Documenter le remboursement',
    'refundHelp':
        'À documenter seulement après le paiement réel. Cette action ne transfère pas d’argent.',
    'refundDate': 'Date comptable du remboursement',
    'refundReference': 'Référence bancaire du remboursement',
    'financeEntry': 'ID d’une dépense existante (facultatif)',
    'financeEntryHelp':
        'Laissez vide pour créer une dépense bancaire ou saisissez l’ID d’une dépense exactement correspondante.',
    'credit_pending': 'Vérification en attente',
    'credit_issued': 'Avoir créé – remboursement en attente',
    'credit_completed': 'Terminé – aucun remboursement requis',
    'credit_refunded': 'Remboursement documenté',
    'credit_withdrawn': 'Retirée',
    'error':
        'L’action n’a pas pu être effectuée. Vérifiez les données et l’état actuel.',
  },
  'ar': {
    'title': 'تحميل الرسوم',
    'help': 'ينشئ المقترح فاتورة منفصلة فقط بعد اعتماد شخص مخول آخر.',
    'current': 'الرسوم الحالية',
    'recipient': 'المستلم',
    'basis': 'أساس المراجعة',
    'reason': 'السبب',
    'due': 'تاريخ الاستحقاق',
    'amount': 'المبلغ المقترح باليورو',
    'account': 'الحساب المحاسبي',
    'proposal': 'إنشاء مقترح',
    'approve': 'اعتماد تحميل الرسوم',
    'cancel': 'سحب المقترح',
    'requestVoid': 'طلب الإلغاء',
    'approveVoid': 'اعتماد الإلغاء',
    'withdrawVoid': 'سحب طلب الإلغاء',
    'basisConfirm': 'راجعت الأساس والمستلم والمبلغ والاستحقاق.',
    'confirm': 'أؤكد هذا الإجراء والبيانات المعروضة.',
    'retry': 'إرسال الطلب نفسه مجدداً',
    'reload': 'تحميل الحالة الحالية',
    'uncertain':
        'نتيجة الطلب غير واضحة. ترسل إعادة المحاولة البيانات نفسها تماماً دون إعادة تلقائية.',
    'review': 'تلزم مراجعة جديدة: تغيرت الرسوم الأساسية.',
    'empty': 'لا توجد مقترحات بعد.',
    'invoice': 'فاتورة منفصلة',
    'voidRequest': 'طلب الإلغاء',
    'status_draft': 'مسودة',
    'status_cancelled': 'مسحوب',
    'status_approved': 'معتمد',
    'status_voided': 'ملغى',
    'status_credited': 'مضاف له رصيد',
    'void_pending': 'قيد الانتظار',
    'void_applied': 'تم الإلغاء',
    'void_withdrawn': 'مسحوب',
    'invoice_open': 'مفتوحة',
    'invoice_overdue': 'متأخرة',
    'invoice_paid': 'مدفوعة',
    'invoice_cancelled': 'ملغاة',
    'requestCredit': 'طلب إشعار دائن',
    'approveCredit': 'اعتماد الإشعار الدائن',
    'withdrawCredit': 'سحب طلب الإشعار الدائن',
    'creditRequest': 'طلب إشعار دائن',
    'creditNote': 'رقم الإشعار الدائن',
    'creditDocument': 'فتح الإشعار الدائن بصيغة PDF',
    'documentError': 'تعذر فتح الإشعار الدائن.',
    'refundDue': 'مبلغ الاسترداد المستحق',
    'refundEvidence': 'إثبات الاسترداد',
    'refund': 'توثيق الاسترداد',
    'refundHelp': 'يوثّق بعد الدفع الفعلي فقط. لا يحوّل هذا الإجراء أي أموال.',
    'refundDate': 'تاريخ قيد الاسترداد',
    'refundReference': 'مرجع بنك الاسترداد',
    'financeEntry': 'معرّف مصروف موجود (اختياري)',
    'financeEntryHelp':
        'اتركه فارغاً لإنشاء مصروف بنكي أو أدخل معرّف مصروف مطابق تماماً.',
    'credit_pending': 'بانتظار المراجعة',
    'credit_issued': 'صدر الإشعار – الاسترداد معلق',
    'credit_completed': 'مكتمل – لا يلزم استرداد',
    'credit_refunded': 'تم توثيق الاسترداد',
    'credit_withdrawn': 'مسحوب',
    'error': 'تعذر إكمال الإجراء. تحقق من البيانات والحالة الحالية.',
  },
};
