import 'package:flutter/material.dart';
import 'package:mobile_scanner/mobile_scanner.dart';

import '../core/airmius_l10n.dart';
import '../widgets/airmius_widgets.dart';

/// Camera-only scanner for the short-lived member-card token.
///
/// The QR payload is deliberately treated as an opaque credential. We accept
/// the app URI generated by [MemberCardScreen] and a raw token for backwards
/// compatibility, but never display or trust member data from the QR itself.
class MemberCardQrScannerScreen extends StatefulWidget {
  const MemberCardQrScannerScreen({required this.clubId, super.key});

  final int clubId;

  @override
  State<MemberCardQrScannerScreen> createState() =>
      _MemberCardQrScannerScreenState();
}

class _MemberCardQrScannerScreenState extends State<MemberCardQrScannerScreen> {
  final MobileScannerController _controller = MobileScannerController(
    detectionSpeed: DetectionSpeed.noDuplicates,
  );
  bool _handled = false;
  String? _status;

  String t(String key) => AirmiusScope.of(context).t(key);

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  Future<void> _onDetect(BarcodeCapture capture) async {
    if (_handled) return;
    for (final barcode in capture.barcodes) {
      final token = _extractToken(barcode.rawValue);
      if (token == null) continue;
      _handled = true;
      await _controller.stop();
      if (!mounted) return;
      Navigator.of(context).pop(token);
      return;
    }
    if (mounted && _status == null) {
      setState(() => _status = t('memberCard.qrInvalid'));
    }
  }

  String? _extractToken(String? rawValue) {
    final raw = rawValue?.trim();
    if (raw == null || raw.isEmpty) return null;

    final uri = Uri.tryParse(raw);
    if (uri != null && uri.queryParameters.containsKey('token')) {
      final club = int.tryParse(
        uri.queryParameters['club_id'] ?? uri.queryParameters['club'] ?? '',
      );
      if (club != null && club != widget.clubId) {
        if (mounted) setState(() => _status = t('memberCard.qrWrongClub'));
        return null;
      }
      final token = uri.queryParameters['token']?.trim();
      return token != null && token.length >= 24 ? token : null;
    }

    // Do not accept arbitrary URLs or member information as credentials.
    if (raw.contains('://') || raw.length < 24 || raw.length > 160) {
      return null;
    }
    return raw;
  }

  @override
  Widget build(BuildContext context) {
    final scheme = Theme.of(context).colorScheme;
    return Scaffold(
      backgroundColor: Colors.black,
      appBar: AppBar(
        title: Text(t('memberCard.scanTitle')),
        backgroundColor: Colors.black,
        foregroundColor: Colors.white,
      ),
      body: Stack(
        fit: StackFit.expand,
        children: [
          MobileScanner(
            controller: _controller,
            onDetect: _onDetect,
            errorBuilder: (context, error) => Center(
              child: Padding(
                padding: const EdgeInsets.all(24),
                child: Text(
                  t('memberCard.cameraError'),
                  textAlign: TextAlign.center,
                  style: const TextStyle(color: Colors.white, height: 1.4),
                ),
              ),
            ),
          ),
          IgnorePointer(
            child: Center(
              child: Container(
                width: 250,
                height: 250,
                decoration: BoxDecoration(
                  border: Border.all(color: scheme.primary, width: 4),
                  borderRadius: BorderRadius.circular(24),
                ),
              ),
            ),
          ),
          Positioned(
            left: 16,
            right: 16,
            bottom: 24,
            child: AirmiusPanel(
              borderColor: scheme.primary.withValues(alpha: .8),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.stretch,
                children: [
                  Text(
                    t('memberCard.scanHint'),
                    textAlign: TextAlign.center,
                    style: const TextStyle(color: Colors.white, height: 1.35),
                  ),
                  if (_status != null) ...[
                    const SizedBox(height: 8),
                    Text(
                      _status!,
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        color: scheme.tertiary,
                        fontWeight: FontWeight.w800,
                      ),
                    ),
                  ],
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }
}
