const copy = {
    de: {
        eyebrow: 'Plattformbetrieb',
        title: 'Vereinsverwaltung',
        intro: 'Alle Vereine der Plattform unabhängig vom eigenen Arbeitsbereich suchen, prüfen und verwalten.',
        open_subscriptions: 'Abo-Verwaltung',
        created: 'Erstellt: {date}',
        created_label: 'Erstellt',
        members: '{count} Mitglieder',
        teams: '{count} Teams',
        members_short: '{count} Mitgl.',
        teams_short: '{count} Teams',
        listed: 'Öffentlich gelistet',
        unlisted: 'Nicht gelistet',
        empty: 'Keine Vereine entsprechen den gewählten Filtern.',
        summary: { total: 'Vereine gesamt', verified: 'Verifiziert', pending: 'In Prüfung', unlisted: 'Nicht gelistet' },
        filters: {
            search: 'Suche',
            search_placeholder: 'Name, Ort, Vereinsnummer oder Eigentümer',
            verification: 'Prüfstatus',
            all_statuses: 'Alle Status',
            apply: 'Anwenden',
            reset: 'Zurücksetzen',
        },
        table: { club: 'Verein', owner: 'Eigentümer', usage: 'Nutzung', status: 'Status', plan: 'Abo', actions: 'Aktionen' },
        status: { verified: 'Verifiziert', pending_verification: 'In Prüfung', rejected: 'Abgelehnt', unknown: 'Unbekannt' },
        status_change: {
            select_label: 'Vereinsstatus ändern',
            title: 'Vereinsstatus ändern',
            message: 'Möchtest du den Status von „{name}“ wirklich von „{from}“ zu „{to}“ ändern?',
            confirm: 'Status ändern',
            success: 'Der Vereinsstatus wurde aktualisiert.',
            error: 'Der Vereinsstatus konnte nicht geändert werden.',
        },
        actions: {
            open_profile: 'Vereinsprofil öffnen',
            open_subscription: 'Abo dieses Vereins öffnen',
            delete: 'Verein endgültig löschen',
        },
        delete: {
            title: 'Verein „{name}“ löschen',
            message: 'Der Verein sowie seine Teams, Mitgliedschaften und operativen Vereinsdaten werden endgültig gelöscht. Diese Aktion kann nicht rückgängig gemacht werden.',
            input_label: 'Zur Bestätigung den Vereinsnamen exakt eingeben',
            confirm: 'Endgültig löschen',
            mismatch: 'Der eingegebene Vereinsname stimmt nicht überein.',
            success: 'Der Verein wurde endgültig gelöscht.',
            error: 'Der Verein konnte nicht gelöscht werden.',
        },
    },
    en: {
        eyebrow: 'Platform operations',
        title: 'Club administration',
        intro: 'Search, review and manage every club on the platform independently of your own workspace.',
        open_subscriptions: 'Subscription management',
        created: 'Created: {date}',
        created_label: 'Created',
        members: '{count} members',
        teams: '{count} teams',
        members_short: '{count} members',
        teams_short: '{count} teams',
        listed: 'Publicly listed',
        unlisted: 'Not listed',
        empty: 'No clubs match the selected filters.',
        summary: { total: 'Total clubs', verified: 'Verified', pending: 'Under review', unlisted: 'Not listed' },
        filters: {
            search: 'Search',
            search_placeholder: 'Name, city, club number or owner',
            verification: 'Review status',
            all_statuses: 'All statuses',
            apply: 'Apply',
            reset: 'Reset',
        },
        table: { club: 'Club', owner: 'Owner', usage: 'Usage', status: 'Status', plan: 'Subscription', actions: 'Actions' },
        status: { verified: 'Verified', pending_verification: 'Under review', rejected: 'Rejected', unknown: 'Unknown' },
        status_change: {
            select_label: 'Change club status',
            title: 'Change club status',
            message: 'Do you really want to change “{name}” from “{from}” to “{to}”?',
            confirm: 'Change status',
            success: 'The club status was updated.',
            error: 'The club status could not be changed.',
        },
        actions: {
            open_profile: 'Open club profile',
            open_subscription: "Open this club's subscription",
            delete: 'Permanently delete club',
        },
        delete: {
            title: 'Delete club “{name}”',
            message: 'The club and its teams, memberships and operational club data will be permanently deleted. This action cannot be undone.',
            input_label: 'Enter the exact club name to confirm',
            confirm: 'Delete permanently',
            mismatch: 'The entered club name does not match.',
            success: 'The club was permanently deleted.',
            error: 'The club could not be deleted.',
        },
    },
    fr: {
        eyebrow: 'Exploitation de la plateforme',
        title: 'Administration des clubs',
        intro: 'Recherchez, contrôlez et gérez tous les clubs de la plateforme, indépendamment de votre propre espace de travail.',
        open_subscriptions: 'Gestion des abonnements',
        created: 'Créé : {date}',
        created_label: 'Créé',
        members: '{count} membres',
        teams: '{count} équipes',
        members_short: '{count} membres',
        teams_short: '{count} équipes',
        listed: 'Répertorié publiquement',
        unlisted: 'Non répertorié',
        empty: 'Aucun club ne correspond aux filtres sélectionnés.',
        summary: { total: 'Total des clubs', verified: 'Vérifiés', pending: 'En cours d’examen', unlisted: 'Non répertoriés' },
        filters: {
            search: 'Recherche',
            search_placeholder: 'Nom, ville, numéro du club ou propriétaire',
            verification: 'Statut de contrôle',
            all_statuses: 'Tous les statuts',
            apply: 'Appliquer',
            reset: 'Réinitialiser',
        },
        table: { club: 'Club', owner: 'Propriétaire', usage: 'Utilisation', status: 'Statut', plan: 'Abonnement', actions: 'Actions' },
        status: { verified: 'Vérifié', pending_verification: 'En cours d’examen', rejected: 'Refusé', unknown: 'Inconnu' },
        status_change: {
            select_label: 'Modifier le statut du club',
            title: 'Modifier le statut du club',
            message: 'Voulez-vous vraiment faire passer « {name} » de « {from} » à « {to} » ?',
            confirm: 'Modifier le statut',
            success: 'Le statut du club a été mis à jour.',
            error: 'Le statut du club n’a pas pu être modifié.',
        },
        actions: {
            open_profile: 'Ouvrir le profil du club',
            open_subscription: 'Ouvrir l’abonnement de ce club',
            delete: 'Supprimer définitivement le club',
        },
        delete: {
            title: 'Supprimer le club « {name} »',
            message: 'Le club, ses équipes, ses adhésions et ses données opérationnelles seront définitivement supprimés. Cette action est irréversible.',
            input_label: 'Saisissez le nom exact du club pour confirmer',
            confirm: 'Supprimer définitivement',
            mismatch: 'Le nom du club saisi ne correspond pas.',
            success: 'Le club a été définitivement supprimé.',
            error: 'Le club n’a pas pu être supprimé.',
        },
    },
    ar: {
        eyebrow: 'تشغيل المنصة',
        title: 'إدارة الأندية',
        intro: 'ابحث عن جميع أندية المنصة وراجعها وأدرها بشكل مستقل عن مساحة عملك الخاصة.',
        open_subscriptions: 'إدارة الاشتراكات',
        created: 'تاريخ الإنشاء: {date}',
        created_label: 'تاريخ الإنشاء',
        members: '{count} أعضاء',
        teams: '{count} فرق',
        members_short: '{count} أعضاء',
        teams_short: '{count} فرق',
        listed: 'مدرج للعامة',
        unlisted: 'غير مدرج',
        empty: 'لا توجد أندية تطابق عوامل التصفية المحددة.',
        summary: { total: 'إجمالي الأندية', verified: 'موثقة', pending: 'قيد المراجعة', unlisted: 'غير مدرجة' },
        filters: {
            search: 'بحث',
            search_placeholder: 'الاسم أو المدينة أو رقم النادي أو المالك',
            verification: 'حالة المراجعة',
            all_statuses: 'جميع الحالات',
            apply: 'تطبيق',
            reset: 'إعادة ضبط',
        },
        table: { club: 'النادي', owner: 'المالك', usage: 'الاستخدام', status: 'الحالة', plan: 'الاشتراك', actions: 'الإجراءات' },
        status: { verified: 'موثق', pending_verification: 'قيد المراجعة', rejected: 'مرفوض', unknown: 'غير معروف' },
        status_change: {
            select_label: 'تغيير حالة النادي',
            title: 'تغيير حالة النادي',
            message: 'هل تريد فعلًا تغيير حالة «{name}» من «{from}» إلى «{to}»؟',
            confirm: 'تغيير الحالة',
            success: 'تم تحديث حالة النادي.',
            error: 'تعذر تغيير حالة النادي.',
        },
        actions: {
            open_profile: 'فتح ملف النادي',
            open_subscription: 'فتح اشتراك هذا النادي',
            delete: 'حذف النادي نهائيًا',
        },
        delete: {
            title: 'حذف النادي «{name}»',
            message: 'سيتم حذف النادي وفرقه وعضوياته وبياناته التشغيلية نهائيًا. لا يمكن التراجع عن هذا الإجراء.',
            input_label: 'أدخل اسم النادي بالكامل للتأكيد',
            confirm: 'حذف نهائي',
            mismatch: 'اسم النادي الذي أدخلته غير مطابق.',
            success: 'تم حذف النادي نهائيًا.',
            error: 'تعذر حذف النادي.',
        },
    },
}

const resolvePath = (source, path) => path
    .split('.')
    .reduce((value, segment) => value?.[segment], source)

export const translateAdminClubs = (locale, key, replacements = {}) => {
    const language = String(locale || 'de').split('-')[0]
    const path = String(key).replace(/^admin_clubs\./, '')
    const value = resolvePath(copy[language] || copy.de, path) ?? resolvePath(copy.de, path) ?? key

    return Object.entries(replacements).reduce(
        (text, [name, replacement]) => String(text).replaceAll(`{${name}}`, replacement),
        value,
    )
}
